# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BasicBitcoinWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BasicBitcoinWallet
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'
  pod 'UICKeyChainStore'
  pod 'MJRefresh'
  pod 'BlocksKit'
  pod 'Toast', '~> 4.0.0'
  target 'BasicBitcoinWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
